### PR TITLE
Next2

### PR DESCRIPTION
**Pull request by jungeebah**
migrating to next js

### CODE REVIEW

**Review by LearningB — APPROVED** [review]

**Comment by LearningB** [comment]
done

**Review by LearningB — COMMENTED** [review]
done

**Review by LearningB — APPROVED** [review]
i approve it

**Review by jungeebah — COMMENTED** [review]
done

**Comment by jungeebah** [comment]
merging the branch

**Review by LearningB — APPROVED** [review]

**Review by LearningB — APPROVED** [review]

**Pull request merged**
